default:
  target: dev
  outputs:
    dev:
      account: '_'         # overwritten by SNOWFLAKE_ACCOUNT GitHub secret
      user: '_'            # overwritten by service user
      database: VENKATESWARLU_AVVARI_COGNIZANT_COM_DB
      schema: dev_schema
      role: VENKATESWARLU_AVVARI_COGNIZANT_COM_ROLE
      type: snowflake
      warehouse: DEMO_WH
    prod:
      account: '_'         # overwritten by SNOWFLAKE_ACCOUNT GitHub secret
      user: '_'            # overwritten by service user
      database: VENKATESWARLU_AVVARI_COGNIZANT_COM_DB
      schema: prod_schema
      role: VENKATESWARLU_AVVARI_COGNIZANT_COM_ROLE
      type: snowflake
      warehouse: DEMO_WH
